% LINES THAT ALWAYS HAVE TO BE: clear variables, close opened windows and 
% clean the comand windows
%-------------------------------------------------------------------------%
clear variables;
close all;
clc;
%-------------------------------------------------------------------------%

%EXERCISE 2:  MODEL OF THE BEHAVIOUR FROM A MOBILE ROBOT IN SIMULINK

% In the following assignments there is going to be used different control
% techniques for the navigation of a mobile robot. Therefore, it is needed
% to give the robot (MR) a certain behaviour, somehow. It is going to be 
% used Simulink with that objective.

% MR's state is defined by its position in the enviroment (xk, yk) and its 
% orientation ?k, where k > 0 is the discrete time. The MR movement is
% ruled by:
% xk = xk-1 + Vk-1 * Ts * cos(?k-1)
% yk = yk-1 + Vk-1 * Ts * cos(?k-1)
% ?k = ?k-1 + ?k-1 * Ts

% Where:
% - Ts is the sampling period used in the system.
% - ?k is the angular speed of the robot.
% - Vk is the linear speed.

% Using Simulink, MR is shown by a block where:
% - Inputs are the speeds (angular and linear).
% - Outputs are its position and orientation.

%                     ____________
%                   >|V           |> x 
%                   >|?           |> y
%                    |____________|> ? (theta)

% The MR block should implement the movement equations using the basic
% blocks from Simuling.

% 1. Implement the movement equations (all used blocks can be found in the
%    standard Simulink's library).

% 2. Once completed the implementation, create a subsystem and simulate its
%    functioning by using linear speed and angular speed with constant
%    values. Configure the parameters of the simulation 
%    (menu "Simulation/Model Simulation Parameters" and 
%     menu "Simulation/Pacing options").

% 3. Visualize the graph generated by the XY Graph module, check if the MR
%    gives the expected results.

% 4. Make another simulation with non-constant angular speeds (these is
%    available in the library Simulink/sources):
%    a. Slope.
%    b. Sinusoidal Variation.

% 5. Study the path followed by the MR and check that they give the
%    expected behaviour.

% 6. Modify the MR initial positon so that it starts moving at the poing
%    (-4, 4)
%    and repeat the simulations.

